/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoolSwitch: typeof import('./src/components/BoolSwitch.vue')['default']
    ComboboxAnchor: typeof import('reka-ui')['ComboboxAnchor']
    ComboboxContent: typeof import('reka-ui')['ComboboxContent']
    ComboboxEmpty: typeof import('reka-ui')['ComboboxEmpty']
    ComboboxInput: typeof import('reka-ui')['ComboboxInput']
    ComboboxItem: typeof import('reka-ui')['ComboboxItem']
    ComboboxItemIndicator: typeof import('reka-ui')['ComboboxItemIndicator']
    ComboboxRoot: typeof import('reka-ui')['ComboboxRoot']
    ComboboxTrigger: typeof import('reka-ui')['ComboboxTrigger']
    ComboboxViewport: typeof import('reka-ui')['ComboboxViewport']
    DialogClose: typeof import('reka-ui')['DialogClose']
    DialogContent: typeof import('reka-ui')['DialogContent']
    DialogDescription: typeof import('reka-ui')['DialogDescription']
    DialogOverlay: typeof import('reka-ui')['DialogOverlay']
    DialogPortal: typeof import('reka-ui')['DialogPortal']
    DialogRoot: typeof import('reka-ui')['DialogRoot']
    DialogTitle: typeof import('reka-ui')['DialogTitle']
    DialogTrigger: typeof import('reka-ui')['DialogTrigger']
    DialogWindow: typeof import('./src/components/DialogWindow.vue')['default']
    IconTrash: typeof import('./src/components/IconTrash.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PaginationEllipsis: typeof import('reka-ui')['PaginationEllipsis']
    PaginationFirst: typeof import('reka-ui')['PaginationFirst']
    PaginationLast: typeof import('reka-ui')['PaginationLast']
    PaginationList: typeof import('reka-ui')['PaginationList']
    PaginationListItem: typeof import('reka-ui')['PaginationListItem']
    PaginationNext: typeof import('reka-ui')['PaginationNext']
    PaginationPrev: typeof import('reka-ui')['PaginationPrev']
    PaginationRoot: typeof import('reka-ui')['PaginationRoot']
    PointSlider: typeof import('./src/components/PointSlider.vue')['default']
    PopoverArrow: typeof import('reka-ui')['PopoverArrow']
    PopoverClose: typeof import('reka-ui')['PopoverClose']
    PopoverContent: typeof import('reka-ui')['PopoverContent']
    PopoverPortal: typeof import('reka-ui')['PopoverPortal']
    PopoverRoot: typeof import('reka-ui')['PopoverRoot']
    PopoverTrigger: typeof import('reka-ui')['PopoverTrigger']
    PropertyDialog: typeof import('./src/components/PropertyDialog.vue')['default']
    SliderRange: typeof import('reka-ui')['SliderRange']
    SliderRoot: typeof import('reka-ui')['SliderRoot']
    SliderThumb: typeof import('reka-ui')['SliderThumb']
    SliderTrack: typeof import('reka-ui')['SliderTrack']
    SplitterGroup: typeof import('reka-ui')['SplitterGroup']
    SplitterPanel: typeof import('reka-ui')['SplitterPanel']
    SplitterResizeHandle: typeof import('reka-ui')['SplitterResizeHandle']
    SvgAxis: typeof import('./src/components/SvgAxis.vue')['default']
    SvgLayer: typeof import('./src/components/SvgLayer.vue')['default']
    SvgRenderer: typeof import('./src/components/SvgRenderer.vue')['default']
    SwitchRoot: typeof import('reka-ui')['SwitchRoot']
    SwitchThumb: typeof import('reka-ui')['SwitchThumb']
    ValueCombo: typeof import('./src/components/ValueCombo.vue')['default']
  }
}
